In [195]:
from   tensorflow.keras.models import Sequential,Model
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from collections import deque
from sklearn import preprocessing
import random

In [196]:
main_data=pd.DataFrame()

In [197]:
currency=['BCH-USD','BTC-USD','ETH-USD','LTC-USD']
for  c in currency:
    dataset='Digital_Currency_data/'+c+'.csv'
    df=pd.read_csv(dataset,names=['time','Low','High','open','Close','Volume'])
    df.rename(columns={'Close':c+'_Close','Volume':c+'_Volume'},inplace=True)
    df.set_index('time',inplace=True)
    df=df[[c+'_Close',c+'_Volume']]
    if len(main_data)==0:
        main_data=df
    else:
        main_data=main_data.join(df)

In [198]:
main_data.head()

,BCH-USD_Close,BCH-USD_Volume,BTC-USD_Close,BTC-USD_Volume,ETH-USD_Close,ETH-USD_Volume,LTC-USD_Close,LTC-USD_Volume
time,,,,,,,,
1528968660,871.719971,5.675361,6489.549805,0.587100,NaN,NaN,96.580002,9.647200
1528968720,870.859985,26.856577,6487.379883,7.706374,486.01001,26.019083,96.660004,314.387024
1528968780,870.099976,1.124300,6479.410156,3.088252,486.00000,8.449400,96.570000,77.129799
1528968840,870.789978,1.749862,6479.410156,1.404100,485.75000,26.994646,96.500000,7.216067
1528968900,870.000000,1.680500,6479.979980,0.753000,486.00000,77.355759,96.389999,524.539978

In [199]:
main_data.isnull().sum()

BCH-USD_Close        0
BCH-USD_Volume       0
BTC-USD_Close     5122
BTC-USD_Volume    5122
ETH-USD_Close      195
ETH-USD_Volume     195
LTC-USD_Close      836
LTC-USD_Volume     836
dtype: int64

In [200]:
main_data.fillna(method='ffill',inplace=True)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_12060\407536374.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  main_data.fillna(method='ffill',inplace=True)

In [201]:
main_data.isnull().sum()

BCH-USD_Close     0
BCH-USD_Volume    0
BTC-USD_Close     0
BTC-USD_Volume    0
ETH-USD_Close     1
ETH-USD_Volume    1
LTC-USD_Close     0
LTC-USD_Volume    0
dtype: int64

In [202]:
main_data.fillna(method='bfill',inplace=True)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_12060\1945591578.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  main_data.fillna(method='bfill',inplace=True)

In [203]:
main_data.isnull().sum()

BCH-USD_Close     0
BCH-USD_Volume    0
BTC-USD_Close     0
BTC-USD_Volume    0
ETH-USD_Close     0
ETH-USD_Volume    0
LTC-USD_Close     0
LTC-USD_Volume    0
dtype: int64

In [204]:
main_data['future']=main_data['LTC-USD_Close'].shift(-3)

In [205]:
main_data.head()

,BCH-USD_Close,BCH-USD_Volume,BTC-USD_Close,BTC-USD_Volume,ETH-USD_Close,ETH-USD_Volume,LTC-USD_Close,LTC-USD_Volume,future
time,,,,,,,,,
1528968660,871.719971,5.675361,6489.549805,0.587100,486.01001,26.019083,96.580002,9.647200,96.500000
1528968720,870.859985,26.856577,6487.379883,7.706374,486.01001,26.019083,96.660004,314.387024,96.389999
1528968780,870.099976,1.124300,6479.410156,3.088252,486.00000,8.449400,96.570000,77.129799,96.519997
1528968840,870.789978,1.749862,6479.410156,1.404100,485.75000,26.994646,96.500000,7.216067,96.440002
1528968900,870.000000,1.680500,6479.979980,0.753000,486.00000,77.355759,96.389999,524.539978,96.470001

In [206]:
def compare(current,future):
    if current>future:
        return 1
    else:
        return 0
main_data['taget']=list(map(compare,main_data['LTC-USD_Close'],main_data['future']))

In [207]:
main_data.head()

,BCH-USD_Close,BCH-USD_Volume,BTC-USD_Close,BTC-USD_Volume,ETH-USD_Close,ETH-USD_Volume,LTC-USD_Close,LTC-USD_Volume,future,taget
time,,,,,,,,,,
1528968660,871.719971,5.675361,6489.549805,0.587100,486.01001,26.019083,96.580002,9.647200,96.500000,1
1528968720,870.859985,26.856577,6487.379883,7.706374,486.01001,26.019083,96.660004,314.387024,96.389999,1
1528968780,870.099976,1.124300,6479.410156,3.088252,486.00000,8.449400,96.570000,77.129799,96.519997,1
1528968840,870.789978,1.749862,6479.410156,1.404100,485.75000,26.994646,96.500000,7.216067,96.440002,1
1528968900,870.000000,1.680500,6479.979980,0.753000,486.00000,77.355759,96.389999,524.539978,96.470001,0

In [208]:
times=sorted(main_data.index.values)

In [209]:
len(times)

92225

In [210]:
int(0.1*len(times))

9222

In [211]:
last_10pct=sorted(main_data.index.values)[-int(0.1*len(times))]

In [212]:
last_10pct

np.int64(1534556340)

In [213]:
main_data_test=main_data[(main_data.index>=last_10pct)]
main_data_train=main_data[(main_data.index<last_10pct)]

In [214]:
len(main_data_test)

9222

In [215]:
len(main_data_train)

83003

In [216]:
main_data['BTC-USD_Close']

time
1528968660    6489.549805
1528968720    6487.379883
1528968780    6479.410156
1528968840    6479.410156
1528968900    6479.979980
                 ...
1535215020    6714.520020
1535215080    6714.520020
1535215140    6715.000000
1535215200    6715.000000
1535215260    6715.000000
Name: BTC-USD_Close, Length: 92225, dtype: float64

In [217]:
main_data['BTC-USD_Close'].pct_change()

time
1528968660         NaN
1528968720   -0.000334
1528968780   -0.001228
1528968840    0.000000
1528968900    0.000088
                ...
1535215020    0.000206
1535215080    0.000000
1535215140    0.000071
1535215200    0.000000
1535215260    0.000000
Name: BTC-USD_Close, Length: 92225, dtype: float64

In [218]:
def preprocess(df):
    df=df.drop('future',axis=1)
    for col in df.columns:
        if col!='target':
            df[col]=df[col].pct_change()
            df.dropna(inplace=True)
            df[col]=preprocessing.scale(df[col].values)
            df.dropna(inplace=True)
        squneces=[]
        prev_d=deque(maxlen=30)
        for i in df.values:
             prev_d.append([n for n in i[:]])
             if len(prev_d)==30:
                 squneces.append([np.array(prev_d),i[-1]])
        random.shuffle(squneces)
        buys=[]
        sells=[]
        for sq,target in squneces:
            if target==0:
                sells.append([sq,target])
            elif target==1:
                buys.append([sq,target])
        random.shuffle(buys)
        random.shuffle(sells)
        lower=min(len(buys),len(sells))
        buys=buys[:lower]
        sells=sells[:lower]
        seq_data=buys+sells
        random.shuffle(seq_data)
        x=[]
        y=[]
        for  seg,target in seq_data:
            x.append(seg)
            y.append(target)
        return np.array(x),np.array(y)

In [219]:
train_x,train_y=preprocess(main_data_train)

In [220]:
train_x.shape

(72318, 30, 9)

In [221]:
train_y.shape

(72318,)

In [222]:
test_x,test_y=preprocess(main_data_test)

In [223]:
test_x.shape

(7580, 30, 9)

In [224]:
np.unique(train_y,return_counts=True)

(array([0., 1.]), array([36159, 36159]))

In [225]:
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.layers import Dense,LSTM,Dropout,BatchNormalization

In [226]:
model=Sequential()
model.add(LSTM(64,input_shape=(30,9)))
model.add(Dense(32,activation='relu'))
model.add(Dense(2,activation='softmax'))

C:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [227]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [228]:
history=model.fit(train_x,train_y,batch_size=100,epochs=100,validation_data=(test_x,test_y))

Epoch 1/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.4993 - loss: 0.6943 - val_accuracy: 0.5191 - val_loss: 0.6916
Epoch 2/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5005 - loss: 0.6938 - val_accuracy: 0.5170 - val_loss: 0.6916
Epoch 3/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5016 - loss: 0.6935 - val_accuracy: 0.4996 - val_loss: 0.6935
Epoch 4/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4971 - loss: 0.6938 - val_accuracy: 0.5182 - val_loss: 0.6919
Epoch 5/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5040 - loss: 0.6938 - val_accuracy: 0.5009 - val_loss: 0.6932
Epoch 6/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4998 - loss: 0.6934 - val_accuracy: 0.5003 - val_loss: 0.6923
Epoch 7/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.4989 - loss: 0.6936 - val_accuracy: 0.5008 - val_loss: 0.6923
Epoch 8/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4993 - loss: 0.6935 - val_accuracy: 0.5012 - val_loss: 0.6922
Epoch 9/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4994 - loss: 0.6934 - val_accuracy: 0.5005 - val_loss: 0.6926
Epoch 10/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4990 - loss: 0.6934 - val_accuracy: 0.4997 - val_loss: 0.6926
Epoch 11/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5004 - loss: 0.6933 - val_accuracy: 0.5001 - val_loss: 0.6926
Epoch 12/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4990 - loss: 0.6932 - val_accuracy: 0.5182 - val_loss: 0.6919
Epoch 13/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5008 - loss: 0.6932 - val_accuracy: 0.4997 - val_loss: 0.6925
Epoch 14/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5013 - loss: 0.6931 - val_accuracy: 0.4997 - val_loss: 0.6928
Epoch 15/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.5000 - loss: 0.6931 - val_accuracy: 0.5185 - val_loss: 0.6922
Epoch 16/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4995 - loss: 0.6931 - val_accuracy: 0.4996 - val_loss: 0.6925
Epoch 17/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5009 - loss: 0.6931 - val_accuracy: 0.4997 - val_loss: 0.6925
Epoch 18/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4986 - loss: 0.6931 - val_accuracy: 0.5178 - val_loss: 0.6925
Epoch 19/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4986 - loss: 0.6931 - val_accuracy: 0.5182 - val_loss: 0.6922
Epoch 20/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4958 - loss: 0.6931 - val_accuracy: 0.5005 - val_loss: 0.6924
Epoch 21/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4961 - loss: 0.6931 - val_accuracy: 0.5175 - val_loss: 0.6929
Epoch 22/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4980 - loss: 0.6931 - val_accuracy: 0.5183 - val_loss: 0.6923
Epoch 23/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5026 - loss: 0.6931 - val_accuracy: 0.4997 - val_loss: 0.6931
Epoch 24/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5017 - loss: 0.6931 - val_accuracy: 0.4997 - val_loss: 0.6925
Epoch 25/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4972 - loss: 0.6931 - val_accuracy: 0.5175 - val_loss: 0.6927
Epoch 26/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5004 - loss: 0.6931 - val_accuracy: 0.5181 - val_loss: 0.6930
Epoch 27/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4993 - loss: 0.6931 - val_accuracy: 0.5170 - val_loss: 0.6933
Epoch 28/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5001 - loss: 0.6931 - val_accuracy: 0.5177 - val_loss: 0.6929
Epoch 29/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5006 - loss: 0.6931 - val_accuracy: 0.5000 - val_loss: 0.6936
Epoch 30/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5021 - loss: 0.6931 - val_accuracy: 0.4819 - val_loss: 0.6943
Epoch 31/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4978 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6939
Epoch 32/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5011 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6929
Epoch 33/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5045 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6941
Epoch 34/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5024 - loss: 0.6930 - val_accuracy: 0.5175 - val_loss: 0.6933
Epoch 35/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.4975 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6939
Epoch 36/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4999 - loss: 0.6930 - val_accuracy: 0.5177 - val_loss: 0.6936
Epoch 37/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 12ms/step - accuracy: 0.4980 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6940
Epoch 38/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5006 - loss: 0.6930 - val_accuracy: 0.5168 - val_loss: 0.6931
Epoch 39/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.4996 - loss: 0.6931 - val_accuracy: 0.5182 - val_loss: 0.6932
Epoch 40/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.4993 - loss: 0.6930 - val_accuracy: 0.4810 - val_loss: 0.6942
Epoch 41/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.5003 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6940
Epoch 42/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.5005 - loss: 0.6930 - val_accuracy: 0.5001 - val_loss: 0.6937
Epoch 43/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.4995 - loss: 0.6930 - val_accuracy: 0.5166 - val_loss: 0.6936
Epoch 44/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.4992 - loss: 0.6930 - val_accuracy: 0.4823 - val_loss: 0.6956
Epoch 45/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.5004 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6940
Epoch 46/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4961 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6937
Epoch 47/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4994 - loss: 0.6930 - val_accuracy: 0.5177 - val_loss: 0.6939
Epoch 48/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5003 - loss: 0.6930 - val_accuracy: 0.5001 - val_loss: 0.6940
Epoch 49/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5007 - loss: 0.6930 - val_accuracy: 0.4999 - val_loss: 0.6940
Epoch 50/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5008 - loss: 0.6930 - val_accuracy: 0.5001 - val_loss: 0.6940
Epoch 51/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5018 - loss: 0.6930 - val_accuracy: 0.4999 - val_loss: 0.6941
Epoch 52/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5016 - loss: 0.6930 - val_accuracy: 0.4822 - val_loss: 0.6949
Epoch 53/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4991 - loss: 0.6930 - val_accuracy: 0.5168 - val_loss: 0.6938
Epoch 54/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5010 - loss: 0.6930 - val_accuracy: 0.5168 - val_loss: 0.6937
Epoch 55/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4998 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6942
Epoch 56/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5013 - loss: 0.6930 - val_accuracy: 0.5166 - val_loss: 0.6938
Epoch 57/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5006 - loss: 0.6930 - val_accuracy: 0.4999 - val_loss: 0.6941
Epoch 58/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.5011 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6943
Epoch 59/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4973 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6944
Epoch 60/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.4994 - loss: 0.6930 - val_accuracy: 0.5166 - val_loss: 0.6940
Epoch 61/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.4986 - loss: 0.6930 - val_accuracy: 0.5148 - val_loss: 0.6943
Epoch 62/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5006 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6942
Epoch 63/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4982 - loss: 0.6930 - val_accuracy: 0.4828 - val_loss: 0.6949
Epoch 64/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4975 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6949
Epoch 65/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4997 - loss: 0.6930 - val_accuracy: 0.4830 - val_loss: 0.6949
Epoch 66/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4964 - loss: 0.6930 - val_accuracy: 0.4830 - val_loss: 0.6949
Epoch 67/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4982 - loss: 0.6930 - val_accuracy: 0.4999 - val_loss: 0.6944
Epoch 68/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.5001 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6946
Epoch 69/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - accuracy: 0.4997 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6948
Epoch 70/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 23s 18ms/step - accuracy: 0.4958 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6947
Epoch 71/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.5010 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6949
Epoch 72/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4986 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6949
Epoch 73/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4989 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6950
Epoch 74/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4978 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6949
Epoch 75/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.5043 - loss: 0.6929 - val_accuracy: 0.4997 - val_loss: 0.6950
Epoch 76/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4987 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6949
Epoch 77/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4987 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6950
Epoch 78/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4987 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6952
Epoch 79/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.4983 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6950
Epoch 80/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.4963 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6950
Epoch 81/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.4970 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6951
Epoch 82/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 21s 26ms/step - accuracy: 0.5010 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6952
Epoch 83/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.4960 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 84/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5017 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6951
Epoch 85/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4971 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6952
Epoch 86/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.5019 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 87/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.4973 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6953
Epoch 88/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5010 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 89/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.5026 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6954
Epoch 90/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4960 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 91/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 20s 27ms/step - accuracy: 0.4987 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6954
Epoch 92/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 12s 17ms/step - accuracy: 0.4993 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6952
Epoch 93/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4990 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 94/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5014 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 95/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4978 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6953
Epoch 96/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.5005 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6953
Epoch 97/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.4999 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 98/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.4997 - loss: 0.6930 - val_accuracy: 0.4997 - val_loss: 0.6952
Epoch 99/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4983 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6952
Epoch 100/100
724/724 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.4989 - loss: 0.6930 - val_accuracy: 0.5000 - val_loss: 0.6953